service: senior-project-template
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
  - serverless-dynamodb
  - serverless-offline

custom:
  dynamodb:
    stages: -dev
    start:
      host: 127.0.0.1
      port: 8000
      docker: false

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          [
            { "AttributeName": "uuid", "AttributeType": "S" },
            { "AttributeName": "startDate", "AttributeType": "S" },
            { "AttributeName": "teamName", "AttributeType": "S" },
          ]
        KeySchema: [{ "AttributeName": "uuid", "KeyType": "HASH" }]
        GlobalSecondaryIndexes:
          [
            {
              "IndexName": "StartDateIndex",
              "KeySchema":
                [{ "AttributeName": "startDate", "KeyType": "HASH" }],
              "Projection": { "ProjectionType": "ALL" },
            },
            {
              "IndexName": "TeamNameIndex",
              "KeySchema": [{ "AttributeName": "teamName", "KeyType": "HASH" }],
              "Projection": { "ProjectionType": "ALL" },
            },
          ]
        BillingMode: PAY_PER_REQUEST
        TableName: users
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    ProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          [{ "AttributeName": "uuid", "AttributeType": "S" }]
        KeySchema: [{ "AttributeName": "uuid", "KeyType": "HASH" }]
        BillingMode: PAY_PER_REQUEST
        TableName: projects
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    DailyStatusTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          [
            { "AttributeName": "uuid", "AttributeType": "S" },
            { "AttributeName": "userId", "AttributeType": "S" },
            { "AttributeName": "date", "AttributeType": "S" },
          ]
        KeySchema: [{ "AttributeName": "uuid", "KeyType": "HASH" }]
        GlobalSecondaryIndexes:
          [
            {
              "IndexName": "userDateIndex",
              "KeySchema":
                [
                  { "AttributeName": "userId", "KeyType": "HASH" },
                  { "AttributeName": "date", "KeyType": "RANGE" },
                ],
              "Projection": { "ProjectionType": "ALL" },
            },
            {
              "IndexName": "dateIndex",
              "KeySchema": [{ "AttributeName": "date", "KeyType": "HASH" }],
              "Projection": { "ProjectionType": "ALL" },
            },
          ]
        BillingMode: PAY_PER_REQUEST
        TableName: dailyStatus
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    AuthTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          [
            { "AttributeName": "uuid", "AttributeType": "S" },
            { "AttributeName": "password", "AttributeType": "S" },
          ]
        KeySchema: [{ "AttributeName": "uuid", "KeyType": "HASH" }]
        GlobalSecondaryIndexes:
          [
            {
              "IndexName": "passwordIndex",
              "KeySchema":
                [{ "AttributeName": "password", "KeyType": "HASH" }],
              "Projection": { "ProjectionType": "ALL" },
            },
          ]
        TableName: authorization
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
functions:
  login:
    handler: src/handlers/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true

  auth:
    handler: src/handlers/auth.handler
    environment:
      AUTH_TABLE: auth
    events:
      - http:
          path: auth
          method: get
          cors: true

  users:
    handler: src/handlers/users.handler
    environment:
      USERS_TABLE: users
    events:
      - http:
          path: users
          method: get
          cors: true

  userById:
    handler: src/handlers/user.handler
    environment:
      USERS_TABLE: users
    events:
      - http:
          path: users/{uuid}
          method: get
          cors: true

  updateUserRoles:
    handler: src/handlers/update-user-roles.handler
    environment:
      USERS_TABLE: users
    events:
      - http:
          path: users/{uuid}/roles
          method: put
          cors: true

  createUser:
    handler: src/handlers/create-user.handler
    environment:
      USERS_TABLE: users
    events:
      - http:
          path: user/create-user
          method: post
          cors: true

  projects:
    handler: src/handlers/projects.handler
    environment:
      PROJECTS_TABLE: projects
    events:
      - http:
          path: projects
          method: get
          cors: true

  importData:
    handler: src/handlers/import-data.handler
    environment:
      USERS_TABLE: users
      PROJECTS_TABLE: projects
      DAILY_STATUS_TABLE: dailyStatus
      AUTH_TABLE: authorization
    events:
      - http:
          path: import-data
          method: post
          cors: true
  postTimeOff:
    handler: src/handlers/post-time-off.handler
    environment:
      USERS_TABLE: users
    events:
      - http:
          path: time-off
          method: post
          cors: true
  getTimeOff:
    handler: src/handlers/get-time-off.handler
    environment:
      USERS_TABLE: users
    events:
      - http:
          path: time-off/{userId}
          method: get
          cors: true
